site_name: IDG Docs
site_url: https://idg-doc.com/
site_author: VNPT-IT

nav:
  - Trang chủ:
    - IDG Portal: index.md
    - Micro Frontend: micro-frontend.md
    - Cài đặt: setup.md
  - Dịch vụ:
    - Hướng dẫn tích hợp: intergration.md
    - Tài liệu tích hợp SDK:
      - Object Storage: services/object-storage.md
      - Kafka: services/kafka.md
      - Redis: services/redis.md
  - Hỗ trợ: support.md
  - Về chúng tôi: about.md

theme:
  name: material
  logo: assets/vnpt-logo.png
  favicon: assets/paper.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.path
  language: vi
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    
      primary: blue
      accent: lime

plugins:
  - search:
      lang:
        - vi
        - en

extra_css:
  - css/style.css

extra_javascript:
  - javascripts/shortcuts.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      title: Mục lục

copyright: |
  &copy; 2023 <a href="http://console.galaxy.vnpt.vn/home/"  target="_blank" rel="noopener">IDG Console</a>